In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Occupancy_Estimation.csv')
df.head()

Date      Time  S1_Temp  S2_Temp  S3_Temp  S4_Temp  S1_Light  \
0  2017/12/22  10:49:41    24.94    24.75    24.56    25.38       121   
1  2017/12/22  10:50:12    24.94    24.75    24.56    25.44       121   
2  2017/12/22  10:50:42    25.00    24.75    24.50    25.44       121   
3  2017/12/22  10:51:13    25.00    24.75    24.56    25.44       121   
4  2017/12/22  10:51:44    25.00    24.75    24.56    25.44       121   

   S2_Light  S3_Light  S4_Light  S1_Sound  S2_Sound  S3_Sound  S4_Sound  \
0        34        53        40      0.08      0.19      0.06      0.06   
1        33        53        40      0.93      0.05      0.06      0.06   
2        34        53        40      0.43      0.11      0.08      0.06   
3        34        53        40      0.41      0.10      0.10      0.09   
4        34        54        40      0.18      0.06      0.06      0.06   

   S5_CO2  S5_CO2_Slope  S6_PIR  S7_PIR  Room_Occupancy_Count  
0     390      0.769231       0       0                     1  
1     390      0.646154       0       0                     1  
2     390      0.519231       0       0                     1  
3     390      0.388462       0       0                     1  
4     390      0.253846       0       0                     1

In [3]:
df.columns

Index(['Date', 'Time', 'S1_Temp', 'S2_Temp', 'S3_Temp', 'S4_Temp', 'S1_Light',
       'S2_Light', 'S3_Light', 'S4_Light', 'S1_Sound', 'S2_Sound', 'S3_Sound',
       'S4_Sound', 'S5_CO2', 'S5_CO2_Slope', 'S6_PIR', 'S7_PIR',
       'Room_Occupancy_Count'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10129 entries, 0 to 10128
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Date                  10129 non-null  object 
 1   Time                  10129 non-null  object 
 2   S1_Temp               10129 non-null  float64
 3   S2_Temp               10129 non-null  float64
 4   S3_Temp               10129 non-null  float64
 5   S4_Temp               10129 non-null  float64
 6   S1_Light              10129 non-null  int64  
 7   S2_Light              10129 non-null  int64  
 8   S3_Light              10129 non-null  int64  
 9   S4_Light              10129 non-null  int64  
 10  S1_Sound              10129 non-null  float64
 11  S2_Sound              10129 non-null  float64
 12  S3_Sound              10129 non-null  float64
 13  S4_Sound              10129 non-null  float64
 14  S5_CO2                10129 non-null  int64  
 15  S5_CO2_Slope       

In [5]:
df.describe()

S1_Temp       S2_Temp       S3_Temp       S4_Temp      S1_Light  \
count  10129.000000  10129.000000  10129.000000  10129.000000  10129.000000   
mean      25.454012     25.546059     25.056621     25.754125     25.445059   
std        0.351351      0.586325      0.427283      0.356434     51.011264   
min       24.940000     24.750000     24.440000     24.940000      0.000000   
25%       25.190000     25.190000     24.690000     25.440000      0.000000   
50%       25.380000     25.380000     24.940000     25.750000      0.000000   
75%       25.630000     25.630000     25.380000     26.000000     12.000000   
max       26.380000     29.000000     26.190000     26.560000    165.000000   

          S2_Light      S3_Light      S4_Light      S1_Sound      S2_Sound  \
count  10129.00000  10129.000000  10129.000000  10129.000000  10129.000000   
mean      26.01629     34.248494     13.220259      0.168178      0.120066   
std       67.30417     58.400744     19.602219      0.316709      0.266503   
min        0.00000      0.000000      0.000000      0.060000      0.040000   
25%        0.00000      0.000000      0.000000      0.070000      0.050000   
50%        0.00000      0.000000      0.000000      0.080000      0.050000   
75%       14.00000     50.000000     22.000000      0.080000      0.060000   
max      258.00000    280.000000     74.000000      3.880000      3.440000   

           S3_Sound      S4_Sound        S5_CO2  S5_CO2_Slope        S6_PIR  \
count  10129.000000  10129.000000  10129.000000  10129.000000  10129.000000   
mean       0.158119      0.103840    460.860401     -0.004830      0.090137   
std        0.413637      0.120683    199.964940      1.164990      0.286392   
min        0.040000      0.050000    345.000000     -6.296154      0.000000   
25%        0.060000      0.060000    355.000000     -0.046154      0.000000   
50%        0.060000      0.080000    360.000000      0.000000      0.000000   
75%        0.070000      0.100000    465.000000      0.000000      0.000000   
max        3.670000      3.400000   1270.000000      8.980769      1.000000   

             S7_PIR  Room_Occupancy_Count  
count  10129.000000          10129.000000  
mean       0.079574              0.398559  
std        0.270645              0.893633  
min        0.000000              0.000000  
25%        0.000000              0.000000  
50%        0.000000              0.000000  
75%        0.000000              0.000000  
max        1.000000              3.000000

In [6]:
df.Room_Occupancy_Count.value_counts()

0    8228
2     748
3     694
1     459
Name: Room_Occupancy_Count, dtype: int64

In [7]:
DateTimeConc = df['Date'] + ' ' + df['Time']
df['DateTime'] = pd.to_datetime(DateTimeConc)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10129 entries, 0 to 10128
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   Date                  10129 non-null  object        
 1   Time                  10129 non-null  object        
 2   S1_Temp               10129 non-null  float64       
 3   S2_Temp               10129 non-null  float64       
 4   S3_Temp               10129 non-null  float64       
 5   S4_Temp               10129 non-null  float64       
 6   S1_Light              10129 non-null  int64         
 7   S2_Light              10129 non-null  int64         
 8   S3_Light              10129 non-null  int64         
 9   S4_Light              10129 non-null  int64         
 10  S1_Sound              10129 non-null  float64       
 11  S2_Sound              10129 non-null  float64       
 12  S3_Sound              10129 non-null  float64       
 13  S4_Sound        

In [9]:
df.drop(columns=['Date','Time'], inplace = True)

In [10]:
df.columns

Index(['S1_Temp', 'S2_Temp', 'S3_Temp', 'S4_Temp', 'S1_Light', 'S2_Light',
       'S3_Light', 'S4_Light', 'S1_Sound', 'S2_Sound', 'S3_Sound', 'S4_Sound',
       'S5_CO2', 'S5_CO2_Slope', 'S6_PIR', 'S7_PIR', 'Room_Occupancy_Count',
       'DateTime'],
      dtype='object')

In [11]:
X = df.drop(columns = ['Room_Occupancy_Count', 'DateTime'], axis = 1)
y = df['Room_Occupancy_Count']

In [12]:
X, y

(       S1_Temp  S2_Temp  S3_Temp  S4_Temp  S1_Light  S2_Light  S3_Light  \
 0        24.94    24.75    24.56    25.38       121        34        53   
 1        24.94    24.75    24.56    25.44       121        33        53   
 2        25.00    24.75    24.50    25.44       121        34        53   
 3        25.00    24.75    24.56    25.44       121        34        53   
 4        25.00    24.75    24.56    25.44       121        34        54   
 ...        ...      ...      ...      ...       ...       ...       ...   
 10124    25.06    25.13    24.69    25.31         6         7        33   
 10125    25.06    25.06    24.69    25.25         6         7        34   
 10126    25.13    25.06    24.69    25.25         6         7        34   
 10127    25.13    25.06    24.69    25.25         6         7        34   
 10128    25.13    25.06    24.69    25.25         6         7        34   
 
        S4_Light  S1_Sound  S2_Sound  S3_Sound  S4_Sound  S5_CO2  S5_CO2_Slope  \
 0  

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

In [14]:
print(X_train)

      S1_Temp  S2_Temp  S3_Temp  S4_Temp  S1_Light  S2_Light  S3_Light  \
831     26.25    26.56    26.00    26.38       150       236       180   
8262    25.81    26.00    25.75    25.94         2         3        13   
5304    25.13    25.13    24.56    25.31         7         7        35   
2420    25.06    25.06    24.44    25.38         5         5        28   
4598    25.31    25.31    24.81    25.63         0         0         0   
...       ...      ...      ...      ...       ...       ...       ...   
5734    25.31    25.31    25.13    25.88        17        20        75   
5191    25.13    25.13    24.56    25.44         5         5        28   
5390    25.06    25.06    24.63    25.50         9        10        45   
860     26.31    26.69    26.06    26.44       150       236       180   
7270    25.31    25.31    24.88    25.75         0         0         0   

      S4_Light  S1_Sound  S2_Sound  S3_Sound  S4_Sound  S5_CO2  S5_CO2_Slope  \
831         10      0.45      0

In [15]:
print(y_train)

831     3
8262    3
5304    0
2420    0
4598    0
       ..
5734    0
5191    0
5390    0
860     3
7270    0
Name: Room_Occupancy_Count, Length: 7596, dtype: int64


In [16]:
from sklearn.naive_bayes import GaussianNB
NB_classifier = GaussianNB()
NB_classifier.fit(X_train, y_train)

GaussianNB()

In [17]:
y_pred = NB_classifier.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_NB = confusion_matrix(y_test, y_pred)
print(cm_NB)
accuracy_score(y_test, y_pred)

[[2003    0    0   37]
 [   0  120    5    0]
 [   0    0  189   11]
 [   9    0   38  121]]


0.9605211212001579

### We will do the same NB classifier but with a standardized features

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_scl = sc.fit_transform(X_train)
X_test_scl = sc.transform(X_test)

In [20]:
NB_classifier_scl = GaussianNB()
NB_classifier_scl.fit(X_train_scl, y_train)

GaussianNB()

In [21]:
y_pred_scl = NB_classifier.predict(X_test_scl)

In [22]:
cm_NB_scl = confusion_matrix(y_test, y_pred_scl)
print(cm_NB_scl)
accuracy_score(y_test, y_pred_scl)

[[   0 2039    0    1]
 [   0  125    0    0]
 [   0  193    0    7]
 [   0  156    0   12]]


0.05408606395578366

### The result for the standardized features seems extremly bad, Not sure if i missed something